### ISSUE TITLE
Honkai API invalid keys

### ISSUE THREAD

**Issue by Neziak** [an-anime-team/anime-game-core#12]
Getting "invalid key" errors for Honkai API requests.
```
{"data":null,"message":"invalid key","retcode":-205}
```

Affected game editions are Global, Sea, Taiwan & Korea.
API requests for China & Japan still work as of now.

https://github.com/an-anime-team/anime-game-core/blob/0fb314b61d1deb1cd281dc6dc041ce27886cf513/src/games/honkai/consts.rs#L34-L43

**Comment by mkrsym1** [comment]
The company appear to have changed the URLs. Please wait for Krypton to update them

**Comment by Neziak** [comment]
Issue has been fixed in 1.17.7 (commit 70688c783bde19943bbe69e906099e794e392ca8). Thanks!
