### ISSUE TITLE
BrownDust2 support??

### ISSUE THREAD

**Issue by karmakarmeghdip** [an-anime-team/anime-game-core#9]
BrownDust2 just released the PC version for the game. It's an amazing game but the official launcher doesn't seem to work properly in Lutris, so an-anime-game launcher would be nice....

**Comment by krypt0nn** [comment]
I have no plans on supporting any more games right now. Once I get more free - expect support for more games to come in the next major core updates (already in a separate branch). The current one is a legacy solution.
